FROM python:3.12-alpine3.21

WORKDIR /

COPY ./api /api

COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY requirements.txt .

RUN pip3 install -r requirements.txt -U --no-cache-dir 

ENTRYPOINT ["/entrypoint.sh"]
